AllCops:
  DisabledByDefault: false
  TargetRubyVersion: 2.2
  TargetRailsVersion: 4.0
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'test/**/*'
    - 'bin/**/*'
    - 'spec/dummy_app/db/**/*'

Security/YAMLLoad:
  Enabled: false

# Limit line length
Metrics/LineLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
